### ISSUE TITLE
data_provider "preview_images()" will change target data signature 

### ISSUE THREAD

**Issue by stonelarge** [AllanYiin/trident#5]
# environment :
``` 
trident 0.7.4.1
Using Pytorch backend.
Image Data Format: channels_first.
Image Channel Order: rgb.
Pytorch version:1.10.2+cu102.
Automatic Mixed Precision Support:True.
Opencv version:4.5.5.
Pillow version:9.0.1.
```
# sample code
```
import glob
import os

import cv2
import trident as T
from trident import *
from trident.models import vgg

os.environ["TRIDENT_BACKEND"] = "pytorch"
data_provider = load_examples_data("superresolution")
data_provider.paired_transform_funcs = [random_crop(256, 256)]

data_provider.traindata.data.image_transform_funcs = [
    add_noise(0.05),
    random_blur(sigma=(0.1, 0.8)),
    resize((64, 64), True),
    # to_low_resolution(2),
    normalize(127.5, 127.5),
]

data_provider.traindata.label.image_transform_funcs = [normalize(127.5, 127.5)]

data, label = data_provider.next()
print("before preview: data_shape=", data.shape, "labe_shape=", label.shape)
print("before preview: ", data_provider.signature)
print("before preview: ", data_provider.image_transform_funcs)
data_provider.preview_images()

print("after preview: ", data_provider.image_transform_funcs)
print("after preview: ", data_provider.signature)
data, label = data_provider.next()
print("after preview + next(): ", "data_shape=", data.shape, "labe_shape=", label.shape)
print("after preview + next(): ", data_provider.signature)
```
# Result
archive file is already existing, donnot need download again.
extraction is finished, donnot need extract again.
get super resolution images :4823
before preview: data_shape= (8, 3, 64, 64) label_shape= (8, 3, 256, 256)
before preview:  data_provider( ) -> lr: Tensor[(None, 3, 64, 64)] (ObjectType.rgb), hr: Tensor[(None, 3, 256, 256)] (ObjectType.rgb) 
before preview:  []

![image](https://user-images.githubusercontent.com/92557665/160398011-a2e7d242-3ac3-4b68-8fab-1cf45cd5bf4a.png)

after preview:  [AddNoise, <function random_blur.<locals>.img_op at 0x7f3c3477e940>, Resize, Normalize]
after preview:  data_provider( ) -> lr: Tensor[(None, 3, 64, 64)] (ObjectType.rgb), hr: Tensor[(None, 3, 256, 256)] (ObjectType.rgb) 
after preview + next():  **data_shape= (8, 3, 64, 64) label_shape= (8, 3, 64, 64)**
after preview + next():  **data_provider( ) -> lr: Tensor[(None, 3, 64, 64)] (ObjectType.rgb), hr: Tensor[(None, 3, 64, 64)] (ObjectType.rgb)** 

# Expected Result
It seems that after `data_provider.preview_images()`, my target date  (as 'hr' label) shape will be changed from  (8, 3, 256, 256) to  (8, 3, 64, 64).  I hope it could be fixed for target data, and only applying `traindata.data.image_transform_funcs` on input data. What can I do to achieve it?

# Anlaysis
`image_transform_funcs` will apply for all `ImageDataset` data. 
![image](https://user-images.githubusercontent.com/92557665/160399055-6071cf74-59b9-417d-9445-869b3da50469.png)

**Comment by AllanYiin** [comment]
Because resize, rescale are spatial transform, they are default paired transform, no matter you put them in image_transform_funcs or paired_transform_funcs. For super-resolution scenario, I design 'ToLowResolution' transform .

[](https://github.com/AllanYiin/DeepBelief_Course5_Examples/blob/master/epoch402_%E8%B6%8A%E6%94%BE%E5%A4%A7%E8%B6%8A%E6%B8%85%E6%99%B0/super_resolution_pytorch.ipynb)

```


data_provider.paired_transform_funcs=[
    RandomTransform(rotation_range=15, zoom_range=0, shift_range=0.02, shear_range=0.02, random_flip=0.15),
    RandomCrop(256, 256)]

data_provider.image_transform_funcs = [
    ToLowResolution(scale=1 / 4),
    Normalize(127.5, 127.5)]

data_provider.traindata.label.image_transform_funcs = [
    Normalize(127.5, 127.5)]

```
